# Generated by Django 3.0.6 on 2020-05-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract',
            field=models.TextField(null=True),
        ),
    ]
